[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "preview"
  HUGO_ENABLEGITINFO = "true"
